language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install -r test-requirements.txt
- pip install .
script:
- python -m unittest tests
- cat README.rst HISTORY.rst | rst2html.py --strict - /dev/null
deploy:
  provider: pypi
  user: idigbio
  password:
    secure: e/ltrIGHu9wZXmi+8XmIaFmyiYz2540UrL129+ezzWRKRTM5FhPguvRO+6epBNGL4+NYZ+BvBiOumC2SCTGzq3ASncCkaCmjAGh8NCPXXblDOkvMGA9qls9sjoJxBCCBhmcY6/QnPOQ59CiSPLIBxru5u2nf4R7peOrzZHJ5o88=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: iDigBio/idigbio-python-client
notifications:
  slack:
    secure: XIUC86fDwnlQjT44v+BXwnB2e+Xa+bY7n9mgo+YM7SnS/xdWMId/0aIRsiQAsbDRLPfnunEu/E8kpQFvRphK3jWv5t2fHnR+HJ/tHfPSralDTCtvAJX019KY0Bkz0xLgFSjtEvX2BeEHY+QRuA8LCRvWFlY2Mnfx7fFkqbWDPNY=
